### PR TITLE
October 5

### PR DESCRIPTION
**Pull request by usa4cc**

### CODE REVIEW

**Review by TJJP — APPROVED** [review]

**Review by TJJP — COMMENTED** [review]
I currently updated a lot of stuff in my repo which would conflict with these changes

**Comment by 2br-2b** [comment]
As long as we're okay with using Google fonts, depending on what we decide for #21, I'll merge the pull request. I'm guessing we'll probably be okay and I'll merge it, but I just want to be sure.

**Comment by usa4cc** [comment]
Yes, if we could please do that it would be great.

If everyone is really scrupulous about that, I can take out the Google
Fonts code.

But I spent a lot of time on this when I was completely busy, so I really
hope the whole thing doesn't go down the wayside.

Also, the document wasn't properly configured before :)

**Comment by 2br-2b** [comment]
Yeah, most of those changes are good changes. I think we'll discuss this on Discord and/or at our next meeting

**Comment by usa4cc** [comment]
Thanks :)

Our Lady of Victory, pray for us!

**Comment by usa4cc** [comment]
Thanks.

**Pull request merged**
